name: diffdrr
channels:
  - conda-forge
  - pytorch
  - pytorch3d
  - nvidia
dependencies:
  - pip
  - pytorch
  - torchvision
  - pytorch3d
  - einops
  - pydicom
  - matplotlib
  - seaborn
  - tqdm
  - imageio
  - fastcore
  - pip:
    - pyvista
    - vtk
    - pytorchse3
