name: diffdrr
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pip
  - pytorch
  - torchvision
  - einops
  - matplotlib
  - seaborn
  - imageio
  - fastcore
  - tqdm
  - scipy
  - pip:
    - pyvista
    - timm
    - torchio
    - vtk
